# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  test:
    name: Test on go ${{ matrix.go_version }} and ${{ matrix.os }}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        go_version: ['1.20', '1.19', '>=1.20']
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go - version:\ ${{matrix.go_version}}
        uses: actions/setup-go@v4
        with:
          go-version: ${{matrix.go_version}}

      - name: Build-DB
        run: docker-compose build

      - name: Create-DB
        run: docker-compose up -d

      - name: Test
        run: go test -v main_test.go

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: go build -v main.go
